#!/usr/bin/env python3
"""Cycle reader: renders the twelve-cycles synthesis chronicle + the A0 cycle
chronicles as a single long-read HTML page. GR-6: generated, never hand-edited.

  python tools/build_cycle_reader.py            # build reader/cycles.html
  python tools/build_cycle_reader.py --serve    # build + serve at :7474
"""
import re, sys, html, pathlib, functools

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "reader"
PORT = 7474

SYNTHESIS = ROOT / "chronicles" / "2026-07-10_the-twelve-cycles.md"
CYCLE_GLOB = "*a0-fable-runtime-cycle-*.md"

CSS = """
:root{--ink:#1a1d21;--soft:#5a6470;--line:#e3ddd2;--bg:#faf7f1;--acc:#7a5c2e}
@media(prefers-color-scheme:dark){:root{--ink:#e8e4dc;--soft:#9aa3ad;--line:#3a3f45;--bg:#17191c;--acc:#c9a86a}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);
font:19px/1.75 Georgia,'Times New Roman',serif}
.wrap{max-width:46rem;margin:0 auto;padding:4rem 1.4rem 8rem}
h1{font-size:2.1rem;line-height:1.2;margin:3.5rem 0 .6rem}
h2{font-size:1.35rem;margin:3rem 0 .8rem;border-bottom:1px solid var(--line);padding-bottom:.4rem}
h3{font-size:1.05rem;margin:2rem 0 .5rem}
p{margin:0 0 1.25rem}hr{border:0;border-top:1px solid var(--line);margin:3rem 0}
em{color:var(--soft)}strong{color:var(--acc)}
.meta{font:14px/1.6 ui-monospace,Consolas,monospace;color:var(--soft);
border:1px solid var(--line);border-radius:8px;padding:.8rem 1rem;margin:1.4rem 0 2.5rem;
overflow-x:auto;white-space:pre-wrap}
.toc{font-size:.95rem;border:1px solid var(--line);border-radius:8px;padding:1rem 1.4rem;margin:2rem 0}
.toc a{color:var(--acc);text-decoration:none}.toc a:hover{text-decoration:underline}
.toc li{margin:.25rem 0}
.chapter{margin-top:5rem;border-top:3px double var(--line);padding-top:1rem}
.small{color:var(--soft);font-size:.85rem}
ul,ol{margin:0 0 1.25rem;padding-left:1.4rem}li{margin:.3rem 0}
"""

def md_to_html(text: str) -> tuple[str, str]:
    """Very small markdown renderer (headings, hr, bold, em, lists, paragraphs).
    Returns (meta_block_html, body_html)."""
    meta = ""
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if m:
        meta = '<div class="meta">%s</div>' % html.escape(m.group(1))
        text = text[m.end():]
    out, para, inlist = [], [], False
    def flush():
        nonlocal para
        if para:
            out.append("<p>%s</p>" % inline(" ".join(para)))
            para = []
    def inline(s):
        s = html.escape(s)
        s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
        s = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"<em>\1</em>", s)
        s = re.sub(r"`(.+?)`", r"<code>\1</code>", s)
        return s
    for line in text.splitlines():
        ls = line.strip()
        if ls.startswith("- "):
            flush()
            if not inlist:
                out.append("<ul>"); inlist = True
            out.append("<li>%s</li>" % inline(ls[2:])); continue
        if inlist and not ls.startswith("- "):
            out.append("</ul>"); inlist = False
        if not ls:
            flush(); continue
        if ls == "---":
            flush(); out.append("<hr>"); continue
        if ls.startswith("### "):
            flush(); out.append("<h3>%s</h3>" % inline(ls[4:])); continue
        if ls.startswith("## "):
            flush(); out.append('<h2 id="%s">%s</h2>' % (slug(ls[3:]), inline(ls[3:]))); continue
        if ls.startswith("# "):
            flush(); out.append("<h1>%s</h1>" % inline(ls[2:])); continue
        para.append(ls)
    flush()
    if inlist:
        out.append("</ul>")
    return meta, "\n".join(out)

def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")

def build():
    OUT.mkdir(exist_ok=True)
    parts = ['<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">',
             "<title>The Twelve Cycles · Fable runtime synthesis</title>",
             "<style>%s</style>" % CSS, '<div class="wrap">']
    meta, body = md_to_html(SYNTHESIS.read_text(encoding="utf-8"))
    cycles = sorted((ROOT / "chronicles").glob(CYCLE_GLOB))
    toc = ['<div class="toc"><strong>appendix · the cycle chronicles</strong><ol>']
    for c in cycles:
        toc.append('<li><a href="#%s">%s</a></li>' % (slug(c.stem), c.stem.replace("_", " · ")))
    toc.append("</ol></div>")
    parts += [meta, body, "".join(toc)]
    for c in cycles:
        cmeta, cbody = md_to_html(c.read_text(encoding="utf-8"))
        parts.append('<div class="chapter" id="%s"><p class="small">%s</p>%s%s</div>'
                     % (slug(c.stem), html.escape(c.name), cmeta, cbody))
    parts.append('<hr><p class="small">generated by tools/build_cycle_reader.py · GR-6: never hand-edit · ledger head L127 · register head C96</p></div>')
    out = OUT / "cycles.html"
    out.write_text("<!doctype html>\n" + "\n".join(parts), encoding="utf-8")
    n = len(cycles)
    print(f"built {out} · synthesis + {n} cycle chronicles")
    return out

if __name__ == "__main__":
    page = build()
    if "--serve" in sys.argv:
        import http.server, functools as ft
        handler = ft.partial(http.server.SimpleHTTPRequestHandler, directory=str(OUT))
        print(f"serving http://localhost:{PORT}/cycles.html  (Ctrl-C to stop)")
        http.server.ThreadingHTTPServer(("127.0.0.1", PORT), handler).serve_forever()
